[project]
name = "intensification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.8.3"
dependencies = [
    "matplotlib==3.2.2",
    "numpy==1.18.5",
    "pandas==1.2.4",
    "scikit-learn==0.23.1",
    "scipy==1.5.0",
    "pytest==6.2.5",
]
